### ISSUE TITLE
Release pinning

### ISSUE THREAD

**Issue by fabaff** [vchinnipilli/kubestriker#14]
In the `requirements.txt` file are the dependencies pinned to specific releases. This is in issue for package maintainers as distributions usually ship later releases or at least different releases.

Any change that you could soften the version constrains?

**Comment by kubestriker** [comment]
Hi @fabaff Thank you for identifying and creating this issue. As requested, I will make the necessary changes and release a new version.

Cheers,

**Comment by fabaff** [comment]
Same as in #15, closed without change. `https://github.com/vchinnipilli/kubestriker/blob/master/requirements.txt` is still at https://github.com/vchinnipilli/kubestriker/commit/6ade9a9e6c59ed805eddf807bffa3edb84e17ee1.
