### ISSUE TITLE
Docker "Provide token : " input 

### ISSUE THREAD

**Issue by geragcp** [vchinnipilli/kubestriker#23]
Hello!

I am trying to run an authenticated scan using the docker image v1.0.0.
It discovers ok based on the kubeconfig but when I get to the prompt that reads
Provide token : 
I can't enter anything. I am trying to paste in a token. Can't type anything either. 
It does say choose one of the below options (use arrow keys) but it falls right through to the prompt.
Am I doing it wrong? 

Thank you

**Comment by Jmainguy** [comment]
I was able to paste it into a docker container just now, when you paste it, it doesn't show what you pasted (presumably to stop shoulder surfers from seeing your secret token, believe this behavior of hiding it is intentional)

**Comment by geragcp** [comment]
Oh, ok. Thank you for clarifying. I will try that.
